import json
import os
import secrets
from pathlib import Path
from typing import Annotated

from fastapi import HTTPException, Security, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from rebel_forge_backend.core.config import Settings, get_settings
from rebel_forge_backend.core.paths import data_path

TokenSet = dict[str, str]

_tokens: TokenSet | None = None
bearer_scheme = HTTPBearer(
    auto_error=False,
    scheme_name="BearerAuth",
    description="Use an owner or viewer token generated by the local token CLI.",
)
BearerCredentials = Annotated[HTTPAuthorizationCredentials | None, Security(bearer_scheme)]


def get_token_file(settings: Settings | None = None) -> Path:
    return data_path(settings or get_settings(), "auth_tokens.json")


def _validate_tokens(value: object) -> TokenSet:
    if not isinstance(value, dict):
        raise ValueError("Auth token file must contain a JSON object")
    owner = value.get("owner")
    viewer = value.get("viewer")
    if not isinstance(owner, str) or not owner or not isinstance(viewer, str) or not viewer:
        raise ValueError("Auth token file must contain non-empty owner and viewer tokens")
    if secrets.compare_digest(owner, viewer):
        raise ValueError("Owner and viewer tokens must differ")
    return {"owner": owner, "viewer": viewer}


def _read_tokens(token_file: Path) -> TokenSet:
    try:
        tokens = _validate_tokens(json.loads(token_file.read_text(encoding="utf-8")))
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        raise RuntimeError(f"Cannot load auth tokens from {token_file}: {exc}") from exc
    token_file.chmod(0o600)
    return tokens


def _load_tokens() -> TokenSet:
    token_file = get_token_file()
    if token_file.exists():
        return _read_tokens(token_file)

    token_file.parent.mkdir(parents=True, exist_ok=True)
    generated = {
        "owner": secrets.token_urlsafe(32),
        "viewer": secrets.token_urlsafe(32),
    }
    temporary_file = token_file.with_name(
        f".{token_file.name}.{os.getpid()}.{secrets.token_hex(8)}.tmp"
    )
    descriptor = os.open(temporary_file, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            json.dump(generated, stream, indent=2)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        try:
            # Linking a fully written file publishes it without overwriting a winner.
            os.link(temporary_file, token_file)
        except FileExistsError:
            return _read_tokens(token_file)
        return generated
    finally:
        temporary_file.unlink(missing_ok=True)


def get_tokens() -> TokenSet:
    global _tokens
    if _tokens is None:
        _tokens = _load_tokens()
    return _tokens


def clear_token_cache() -> None:
    global _tokens
    _tokens = None


def _extract_token(credentials: HTTPAuthorizationCredentials | None) -> str | None:
    return credentials.credentials if credentials else None


def _matches(candidate: str | None, expected: str) -> bool:
    return candidate is not None and secrets.compare_digest(candidate, expected)


def _unauthorized(detail: str = "Valid Bearer token required") -> HTTPException:
    return HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail=detail,
        headers={"WWW-Authenticate": "Bearer"},
    )


def require_owner(credentials: BearerCredentials) -> str:
    token = _extract_token(credentials)
    tokens = get_tokens()
    if _matches(token, tokens["owner"]):
        return "owner"
    if _matches(token, tokens["viewer"]):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Owner role required")
    raise _unauthorized("Owner token required")


def require_viewer(credentials: BearerCredentials) -> str:
    token = _extract_token(credentials)
    tokens = get_tokens()
    if _matches(token, tokens["owner"]):
        return "owner"
    if _matches(token, tokens["viewer"]):
        return "viewer"
    raise _unauthorized()
