import json
import stat
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from rebel_forge_backend.api import auth
from rebel_forge_backend.auth_tokens import main as print_tokens
from rebel_forge_backend.core.config import get_settings


def test_health_uses_real_database_dependency(client: TestClient) -> None:
    response = client.get("/health")

    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_owner_endpoint_distinguishes_unauthorized_and_forbidden(
    client: TestClient,
    viewer_headers: dict[str, str],
) -> None:
    missing = client.get("/v1/config")
    invalid = client.get("/v1/config", headers={"Authorization": "Bearer invalid"})
    viewer = client.get("/v1/config", headers=viewer_headers)

    assert missing.status_code == 401
    assert missing.headers["www-authenticate"] == "Bearer"
    assert invalid.status_code == 401
    assert viewer.status_code == 403
    assert viewer.json()["detail"] == "Owner role required"


def test_owner_can_access_protected_endpoint(
    client: TestClient, owner_headers: dict[str, str]
) -> None:
    response = client.get("/v1/config", headers=owner_headers)

    assert response.status_code == 200
    assert response.json()["app_env"] == "test"


def test_login_accepts_each_role_and_rejects_invalid_credentials(
    client: TestClient, tokens: dict[str, str]
) -> None:
    owner = client.post("/v1/auth/login", json={"password": tokens["owner"]})
    viewer = client.post("/v1/auth/login", json={"password": tokens["viewer"]})
    invalid = client.post("/v1/auth/login", json={"password": "wrong"})

    assert owner.json() == {"token": tokens["owner"], "role": "owner"}
    assert viewer.json() == {"token": tokens["viewer"], "role": "viewer"}
    assert invalid.status_code == 401


def test_tokens_are_not_exposed_over_http(client: TestClient) -> None:
    assert client.get("/v1/auth/tokens").status_code == 404


def test_openapi_declares_bearer_authentication(client: TestClient) -> None:
    schema = client.get("/openapi.json").json()

    assert schema["components"]["securitySchemes"]["BearerAuth"] == {
        "type": "http",
        "description": "Use an owner or viewer token generated by the local token CLI.",
        "scheme": "bearer",
    }
    assert schema["paths"]["/v1/config"]["get"]["security"] == [{"BearerAuth": []}]


def test_first_run_tokens_are_persistent_and_owner_only(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setenv("DATA_BASE_PATH", str(tmp_path))
    get_settings.cache_clear()
    auth.clear_token_cache()

    first = auth.get_tokens()
    token_file = auth.get_token_file()
    mode = stat.S_IMODE(token_file.stat().st_mode)
    auth.clear_token_cache()
    second = auth.get_tokens()

    assert first == second
    assert first["owner"] != first["viewer"]
    assert mode == 0o600
    assert json.loads(token_file.read_text()) == first


def test_invalid_token_file_fails_closed(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setenv("DATA_BASE_PATH", str(tmp_path))
    get_settings.cache_clear()
    auth.clear_token_cache()
    auth.get_token_file().write_text("not json", encoding="utf-8")

    with pytest.raises(RuntimeError, match="Cannot load auth tokens"):
        auth.get_tokens()


def test_local_token_cli_prints_bootstrap_tokens(capsys, tokens: dict[str, str]) -> None:
    print_tokens()

    output = capsys.readouterr().out
    assert f"Owner token: {tokens['owner']}" in output
    assert f"Viewer token: {tokens['viewer']}" in output
